### ISSUE TITLE
Support promise factories.

### ISSUE THREAD

**Issue by conartist6** [matthis-d/react-promise-wrapper#3]
Right now usage of this component triggers fetching once at module load time.

I think a more common use case is to want to create a component that starts fetching data when it is instantiated. A top level component will still only do it once, and now you'd be able to have something like this:

```
class User extends Component {}
export default withPromises(props => ({user: fetch(`/user/${props.userId}`)}));
```

**Comment by matthis-d** [comment]
@conartist6 I think your PR #4 fixed this issue.
Please re-open this issue if I'm wrong.

Thank you
